//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XElement.CloudSyncHelper.UI.Win32.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XElement.CloudSyncHelper.UI.Win32.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Header {
            get {
                return ResourceManager.GetString("About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ApplicationMenu_About {
            get {
                return ResourceManager.GetString("ApplicationMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ApplicationMenu_Settings {
            get {
                return ResourceManager.GetString("ApplicationMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterUC_Watermark_Text {
            get {
                return ResourceManager.GetString("FilterUC_Watermark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string MenuBarUC_FilterButton_Tooltip {
            get {
                return ResourceManager.GetString("MenuBarUC_FilterButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud provider:.
        /// </summary>
        public static string ProgramDetails_CloudProvider {
            get {
                return ResourceManager.GetString("ProgramDetails_CloudProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating system configurations:.
        /// </summary>
        public static string ProgramDetails_OsConfigs {
            get {
                return ResourceManager.GetString("ProgramDetails_OsConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration available.
        /// </summary>
        public static string ProgramHeader_ConfigAvailable {
            get {
                return ResourceManager.GetString("ProgramHeader_ConfigAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is stored in cloud.
        /// </summary>
        public static string ProgramHeader_IsInCloud {
            get {
                return ResourceManager.GetString("ProgramHeader_IsInCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string ProgramHeader_IsInstalled {
            get {
                return ResourceManager.GetString("ProgramHeader_IsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked.
        /// </summary>
        public static string ProgramHeader_IsLinked {
            get {
                return ResourceManager.GetString("ProgramHeader_IsLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data stored in cloud yet.
        /// </summary>
        public static string ProgramHeader_IsNotInCloud {
            get {
                return ResourceManager.GetString("ProgramHeader_IsNotInCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not installed.
        /// </summary>
        public static string ProgramHeader_IsNotInstalled {
            get {
                return ResourceManager.GetString("ProgramHeader_IsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not linked.
        /// </summary>
        public static string ProgramHeader_IsNotLinked {
            get {
                return ResourceManager.GetString("ProgramHeader_IsNotLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create link.
        /// </summary>
        public static string ProgramHeader_Link {
            get {
                return ResourceManager.GetString("ProgramHeader_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move data to cloud.
        /// </summary>
        public static string ProgramHeader_MoveToCloud {
            get {
                return ResourceManager.GetString("ProgramHeader_MoveToCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration available.
        /// </summary>
        public static string ProgramHeader_NoConfigAvailable {
            get {
                return ResourceManager.GetString("ProgramHeader_NoConfigAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove link.
        /// </summary>
        public static string ProgramHeader_Unlink {
            get {
                return ResourceManager.GetString("ProgramHeader_Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soon available..
        /// </summary>
        public static string Settings_Placeholder {
            get {
                return ResourceManager.GetString("Settings_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current operating system:.
        /// </summary>
        public static string StatusBar_CurrentOs {
            get {
                return ResourceManager.GetString("StatusBar_CurrentOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no configuration available for {0}.
        /// </summary>
        public static string SupportedOperatingSystem_OsIsNotSupported_StringFormat {
            get {
                return ResourceManager.GetString("SupportedOperatingSystem_OsIsNotSupported_StringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a configuration for {0} available.
        /// </summary>
        public static string SupportedOperatingSystem_OsIsSupported_StringFormat {
            get {
                return ResourceManager.GetString("SupportedOperatingSystem_OsIsSupported_StringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries found..
        /// </summary>
        public static string SyncObjects_NoEntries_Text {
            get {
                return ResourceManager.GetString("SyncObjects_NoEntries_Text", resourceCulture);
            }
        }
    }
}
